name: Dependabot Jira

on:
  pull_request:
    types:
      - opened
    branches:
      - master

jobs:
  create_jira:
    name: Dependabot Jira
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
    - name: Login to Jira
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.SERVICES_PLATFORM_JIRA_URL }}
        JIRA_USER_EMAIL: ${{ secrets.SERVICES_PLATFORM_JIRA_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.SERVICES_PLATFORM_JIRA_API_TOKEN }}

    - name: Create Jira Issue
      id: create
      uses: atlassian/gajira-create@v2.0.1
      with:
        project: DP
        issuetype: Tech Debt
        summary: |
          [${{ github.event.repository.name }}] ${{ github.event.pull_request.title }}
        description: |
          [ServicesPlatformDependabot] ${{ github.event.pull_request.html_url }}
